.Dd 2023
.Dt SHITE 1
.Os
.Sh NAME
.Nm shite
.Nd posix shell, static webpages generator
.Sh SYNOPSIS
.Nm
.Ar SRCDIR
.Ar DESTDIR
.Sh DESCRIPTION
.Nm
is a script to generate a static web page, optionally with blog and/or multiple
pages, by reading a bunch of markdown files and a simple config file.  Made to
facilitate blogging, writing and publication of online content. Since markdown
format is almost pure text, it can prevent the author from contact with ugly html
pages.  It is a very static program, offering little easy customization of the
final product. It will point all your pages to a "style.css" and "favicon.ico" file, that should be placed on the
main directory. With style.css you can customize your website, there is a working 
example on shite sources, just copy the file to the folder of your website.
.Sh ENVIRONMENT
.Ev MARKDOWN
enviroment variable is used to generate html pages.
.Sh FILES
.Pa SRCDIR
- where the site source is, specified by command flag
.Pp
.Pa SRCDIR/foo.md
- these markdown files on the mair dir will be linked as
pages on the naviagtion bar. As an example, this can be used
to create a contact's page, by creating a contact.md file.
.Pp
.Pa SRCDIR/foo.link
- link files. Each '.link' file will be a simple link in the navigation bar, poiting
to the site or file written on the first line.
.Pp
.Pa SRCDIR/shiterc
- the basic site configuration, where you set the title, subtitle, and footer text,
write these things in markdown, as done in the example.
.Pp
.Pa SRCDIR/BLOGDIR
- the root directory of your blog posts, this is set in shiterc, you chan chose any name.
If this folder do not exists, no blog will
be generated neither linked to the navigation bar.
.Pp
.Pa SRCDIR/BLOGDIR/'Category 1'/
- a folder which will hold your posts in a specific category. The folder name will be a section on blog index.
.Pp
.Pa SRCDIR/BLOGDIR/'Section Name'/n-post-name.md
- your blogpost into a specific section of your blog, written in markdown.
The number n on the name will determine the order the post will appear. 
The first two lines of the file must be the name and the date,
in this format:
.Bd -literal -offset left
#Title
1234/12/12
.Ed
.Pp
.Pa SRCDIR/BLOGDIR/'Section Name'/n-linkname.link
- this file will generate a blog entry on the specific section with a link to a file or webpage.
This is useful as an example for posting pdf files. The first two lines of this file have to be the title and date
as the markdown files. In the third line you add the link.
.Bd -literal -offset left
#Link title 
1234/12/12
https://www.link.com
.Ed
.Pp

.Sh EXAMPLES
You can start your site on top of the example site. Just run:
.Bd -literal -offset left
.Nm mkdir dest
.Nm Pa exemplesite/ dest/
.Nm cp exemplesite/style.css exemplesite/favicon.ico dest/
.Pp
And your site will be ready on dest/index.html
.Pp
You will need to copy the "style.css" and "favicon.ico" file to the destination 
dir only once.
.Sh SHITERC
Your site source
.Em must
have a shiterc file on it, this file will contain the "title", "subtitle", "footer"
and "blogdir" info of your site. You can add a file with some script (e.g. disquss)
on SRCDIR and point that file on shiterc with the variable "comment_script", this 
script will be on the footer of all your BLOGDIR pages. 
You can ignore BLOGDIR if you don't have one. You can set BLOGDIR to anything
you want the page with your articles to be called.
.Ed
.Sh SEE ALSO
.Xr smu 1
.Sh AUTHORS
.An Henrique Lengler Aq Mt hleng@tutanota.com
.Sh SECURITY CONSIDERATIONS
.Nm
should not delete any files, only overwrite used files.
