.Dd 2016
.Dt SHITE 1
.Os
.Sh NAME
.Nm shite
.Nd posix shell, static webpages generator
.Sh SYNOPSIS
.Nm
.Ar SRCDIR
.Ar DESTDIR
.Sh DESCRIPTION
.Nm
is a script to generate a static web page, optionally with blog and/or multiple
pages, by reading a bunch of markdown files and a simple config file.  Made to
facilitate blogging, writing and publication of online content, since markdown
format is almost pure text, it can prevent the author from contact with ugly html
pages.  It is a very static program, offering little easy customization of the
final product. It will point all you pages to a "style.css" and "favicon.ico" on the
main directory. With style.css you can customize your website, there is a working 
example on shite sources, just copy the file to the folder of your website.
.Sh ENVIRONMENT
.Ev MARKDOWN
enviroment variable is used to generate html pages.
.Ev EDITOR
will be used on the -p option, to write the post
.Sh FILES
.Pa SRCDIR
- where the site source is, specified by command flag
.Pp
.Pa SRCDIR/foo.md
- markdown files of the main dir. You can write "infinite" ones, each will be
linked to the navigation bar. These files have no specific syntax, just pure markdown.
.Pp
.Pa SRCDIR/foo.link
- link files. each .link file will be a simple link in the navigation bar, poiting
to the site you write in the first line of it.
.Pp
.Pa SRCDIR/shiterc
- the basic site configuration, where you set the title, subtitle, and footer text,
write these things in markdown, as done in the example.
.Pp
.Pa SRCDIR/blog/
- the blog folder, create it if you want one. If you don't create it, blog will
not be generated nor linked to the navbar.
.Pp
.Pa SRCDIR/blog/"Section Name"
- a folder which will hold your posts. The folder name will be a section on blog index.
.Pp
.Pa SRCDIR/blog/"Section Name"/n-post-name.md
- your blogposts, write in markdown. The first two lines must be the name and the date,
in this format:
.Bd -literal -offset left
# Title
1234/12/12
.Ed

the second line is the date of the post. Put a number on the beginning of the name to adjust the order.
.Sh EXAMPLES
You can start your site on top of the example site. Copy it to anywhere (or keep 
it in place), edit shiterc. After that 
run shite to build it, you can point directly to a server dir, for example:
.Bd -literal -offset left
.Nm Pa share/mysite /var/www/htdocs/...
.Pp
You will need to copy the "style.css" and "favicon.ico" file to the destination 
dir only once.
.Sh SHITERC
Your site 
.Em must
have a shiterc file on it, this file will contain the "title", "subtitle", "footer"
and "blogdir" info of your site. You can add a file with some script (e.g. disquss)
on SRCDIR and point that file on shiterc with the variable "comment_script", this 
script will be on the footer of all your BLOGDIR pages. 
You can ignore BLOGDIR if you don't have one. You can set BLOGDIR to anything
you want the page with your articles to be called.
.Ed
.Sh SEE ALSO
.Xr smu 1
.Sh AUTHORS
.An Henrique N. Lengler Aq Mt henriqueleng@openmailbox.org
.Sh SECURITY CONSIDERATIONS
.Nm
should not delete any files, only overwrite used files.
