.Dd 2016
.Dt SHITE 1
.Os
.Sh NAME
.Nm shite
.Nd posix shell, static webpages generator
.Sh SYNOPSIS
.Nm
.Op Fl p
.Ar SRCDIR
.Ar DESTDIR
.Sh DESCRIPTION
.Nm
is a script to generate a static web page, optionally with blog and/or multiple
pages, by reading a bunch of markdown files and a simple config file.  Made to
facilitate blogging, writing and publication of online content, since markdown
format is almost pure text, it can prevent the author from contact with ugly html
pages.  It is a very static program, offering little easy customization of the
final product, to generate anything way different, one will need to edit style.css
file.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl p
Create a blogpost. It will ask for a title, get the date and open your editor on the
new post file. With this option you only need to specify the SRCDIR, if there isn't
a $BLOGDIR, shite will create one,
.Nm
will create it.
.El
.Sh ENVIRONMENT
.Ev MARKDOWN
enviroment variable is used to generate html pages.
.Ev EDITOR
will be used on the -p option, to write the post
.Sh FILES
.Pa SRCDIR
- where the site source is, specified by command flag
.Pp
.Pa SRCDIR/foo.md
- markdown files of the main dir. You can write "infinite" ones, each will be
linked to the navigation bar. These files have no specific syntax, just pure markdown.
.Pp
.Pa SRCDIR/foo.link
- link files. each .link file will be a simple link in the navigation bar, poiting
to the site you write in the first line of it.
.Pp
.Pa SRCDIR/shiterc
- the basic site configuration, where you set the title, subtitle, and footer text,
write these things in markdown, as done in the example.
.Pp
.Pa SRCDIR/favicon.ico
- the icon of your site,
.Nm
will copy it to DESTDIR.
.Pp
.Pa SRCDIR/blog/
- the blog folder, create it if you want one. If you don't create it, blog will
not be generated nor linked to the navbar.
.Pp
.Pa SRCDIR/blog/n-post-name.md
- your blogposts, these files needs to follow a specific format, created by -p
flag. n means a number, this number will say in each time order the posts were
created. The first line of the file
.Sy must
be the name of the post in a <h1> mardown format, like '# Some title', followed
by the date of the post in the next line. To avoid errors, invoke -p flag.
.Sh EXAMPLES
You can start your site on top of the example site. Copy it to anywhere (or keep 
it in place), edit shiterc, remove the blogposts or just edit them. After that 
run shite to build it, you can point directly to a server dir, for example:
.Bd -literal -offset left
.Nm Pa share/mysite /var/www/htdocs/...
To simplify everything you can add add an alias like 'alias buildsite='shite foo bar''
or create a script and add it to crontab to automatically build and upload to the server.
.Ed
.Sh SEE ALSO
.Xr smu 1
.Sh AUTHORS
.An Henrique N. Lengler Aq Mt henriqueleng@openmailbox.org
.Sh SECURITY CONSIDERATIONS
This software runs a lot of commands and can cause damage to the system, since it 
is a new piece and probably there still some bugs to be found: So please use with caution.
